### ISSUE TITLE
Not working for head call

### ISSUE THREAD

**Issue by naturedamends** [iFaxity/wait-on-action#103]
```
   - uses: iFaxity/wait-on-action@v1.1.0
        with:
          resource: http://localhost:3000
          timeout: '20s'
          verbose: true
          tcpTimeout: 10s
          httpTimeout: 10s
          log: true
```

Run iFaxity/wait-on-action@v1.1.0
  with:
    resource: http://localhost:3000
    timeout: [2](https://github.com/owner/repo/actions/runs/12816926194/job/35738974705#step:11:2)0s
    verbose: true
    tcpTimeout: 10s
    httpTimeout: 10s
    delay: 0
    interval: 250
    log: false
    reverse: false
    window: 750
waiting for 1 resources: http://localhost:[3](https://github.com/owner/repo/actions/runs/12816926194/job/35738974705#step:11:3)000
making HTTP(S) head request to  url:http://localhost:3000 ...
wait-on(2017) timed out waiting for: http://localhost:3000; exiting with error
Error: Error: Timeout
  HTTP(S) result for http://localhost:3000: ***
  status: 200,
  statusText: 'OK',
  headers: ***
    'x-powered-by': 'Express',
    'content-type': 'text/plain; charset=utf-8',
    'content-length': '2',
    etag: 'W/"2-nOO9QiTIwXgNtWtBJezz8kv3SLc"',
    date: 'Thu, 16 Jan 202[5](https://github.com/owner/repo/actions/runs/12816926194/job/35738974705#step:11:5) 20:20:13 GMT',
    connection: 'keep-alive',
    'keep-alive': 'timeout=5'
  ***,
  data: ''
***
