### ISSUE TITLE
Version 1.2.0 raises TypeError  

### ISSUE THREAD

**Issue by Hoxbro** [iFaxity/wait-on-action#23]
I just tried to update to version 1.2.0 in our CI and got this error:

![image](https://github.com/iFaxity/wait-on-action/assets/19758978/bc85dedf-9445-4169-b068-7351b1fb0cb7)

This  works on  v1.1.0

``` yaml
  - name: Wait for JupyterLab
    uses: ifaxity/wait-on-action@v1.2.0
    with:
      resource: http-get://localhost:8887/lab
      timeout: 180000
```

The run: https://github.com/holoviz/panel/actions/runs/8811214270/job/24184864579?pr=6775
